import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Candidate, HealResult } from "./types.js";

/**
 * github-plan converts the analysis output (HealResult[]) into a delivery plan
 * for GitHub. It NEVER touches git, the working tree, or the network — it only
 * emits artifacts (PR/issue bodies + a machine-readable manifest) that the
 * `scripts/open-github.sh` driver then turns into a PR or issue via the `gh` CLI.
 *
 * Split of responsibilities:
 *   - HEALED (confident, unambiguous)  -> a single aggregated pull request.
 *   - everything else (AMBIGUOUS / ELEMENT_REMOVED / HEAL_FAILED) -> one issue
 *     per failing test, documenting the drift and candidate scores for a human.
 *
 * The fix is applied on a dedicated branch by the driver — the user's current
 * branch and working tree are never mutated.
 */

export interface GithubPlanOptions {
  /** Directory to write artifacts into. Created if missing. */
  outDir: string;
  /** Target repo as `owner/repo`. Optional — the driver falls back to the origin remote. */
  repo?: string;
  /** Base branch for the PR. Optional — the driver falls back to the repo default. */
  base?: string;
  /** Branch-name prefix for the heal PR. Default `playwright-heal`. */
  branchPrefix?: string;
  /** Labels to apply to created issues. Default `["playwright", "test-maintenance"]`. */
  issueLabels?: string[];
  /** Deterministic id (e.g. a timestamp) for branch/file naming. Default: current UTC compact timestamp. */
  runId?: string;
}

export interface PrRewrite {
  file: string;
  api: string;
  /** The old raw selector string to replace. */
  old: string;
  /** The replacement locator call, e.g. `getByRole('button', { name: 'Place order' })`. */
  new: string;
  confidence?: number;
}

export interface PrPlan {
  title: string;
  /** Path (within outDir) to the rendered PR body markdown. */
  bodyFile: string;
  /** Suggested head branch name. */
  branch: string;
  base?: string;
  /** Per-locator rewrite instructions the driver replays on the branch. */
  rewrites: PrRewrite[];
}

export interface IssuePlan {
  title: string;
  /** Path (within outDir) to the rendered issue body markdown. */
  bodyFile: string;
  labels: string[];
  status: HealResult["status"];
  testFile: string;
}

export interface GithubPlan {
  /** Single aggregated PR for all confident heals, or null when none. */
  pr: PrPlan | null;
  /** One issue per non-healable drift. */
  issues: IssuePlan[];
  repo?: string;
  generatedAt: string;
}

function compactTimestamp(d = new Date()): string {
  return d.toISOString().replace(/[-:]/g, "").replace(/\..+$/, "").replace("T", "-");
}

function shortLocator(s: string): string {
  return s.length > 60 ? s.slice(0, 57) + "..." : s;
}

function candidateTable(candidates: Candidate[]): string {
  if (candidates.length === 0) return "_No candidate elements scored above noise level._";
  const rows = candidates
    .slice(0, 5)
    .map(
      (c) =>
        `| \`${c.locator}\` | ${c.score} | ${(c.confidence * 100).toFixed(0)}% |`,
    )
    .join("\n");
  return ["| Candidate locator | Score | Confidence |", "| --- | --- | --- |", rows].join("\n");
}

function renderPrBody(rewrites: PrRewrite[]): string {
  const lines: string[] = [];
  lines.push("## 🩹 Playwright locator auto-heal");
  lines.push("");
  lines.push(
    "A UI change (class rename, `id` swap, tag/DOM-shape refactor) drifted one or more " +
      "Playwright locators. This PR replaces the broken locators with the most stable " +
      "semantic equivalents the healer could resolve in the new DOM.",
  );
  lines.push("");
  lines.push("> Generated by the `playwright-ui-locator` skill. **Review before merging** —");
  lines.push("> re-run the affected suite locally / in CI to confirm green.");
  lines.push("");
  lines.push("### Healed locators");
  lines.push("");
  lines.push("| File | Old locator | New locator | Confidence |");
  lines.push("| --- | --- | --- | --- |");
  for (const r of rewrites) {
    const conf = r.confidence != null ? `${(r.confidence * 100).toFixed(0)}%` : "—";
    lines.push(
      `| \`${r.file}\` | \`.${r.api}('${shortLocator(r.old)}')\` | \`${r.new}\` | ${conf} |`,
    );
  }
  lines.push("");
  lines.push("### How each replacement was chosen");
  lines.push("");
  lines.push(
    "Class selectors are never emitted — they are the failure mode this skill exists to " +
      "escape. Replacements are preferred in order: `getByTestId` → `getByRole` → " +
      "`getByLabel`/`getByPlaceholder` → `getByText` → `#id` → other `data-*` → CSS path.",
  );
  lines.push("");
  return lines.join("\n") + "\n";
}

function renderIssueBody(result: HealResult): string {
  const f = result.failing;
  const lines: string[] = [];
  const headline: Record<HealResult["status"], string> = {
    HEALED: "Locator drift (healed)",
    HEAL_FAILED: "Locator drift could not be auto-healed",
    ELEMENT_REMOVED: "Locator drift — target element appears removed",
    AMBIGUOUS: "Locator drift — replacement is ambiguous",
  };
  lines.push(`## 🔧 ${headline[result.status]}`);
  lines.push("");
  lines.push(`A Playwright test is failing because its locator no longer resolves, and the`);
  lines.push(`healer could **not** safely pick a replacement. Manual triage is needed.`);
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("| --- | --- |");
  lines.push(`| Test file | \`${f.testFile}\`${f.line ? `:${f.line}` : ""} |`);
  lines.push(`| Broken locator | \`.${f.api}('${shortLocator(f.rawSelector)}')\` |`);
  lines.push(`| Heal status | \`${result.status}\` |`);
  lines.push("");
  if (f.message) {
    lines.push("### Playwright error");
    lines.push("");
    lines.push("```");
    lines.push(f.message.trim());
    lines.push("```");
    lines.push("");
  }
  lines.push("### Candidate elements in the new DOM");
  lines.push("");
  lines.push(candidateTable(result.candidates));
  lines.push("");
  lines.push("### Suggested next steps");
  lines.push("");
  if (result.status === "ELEMENT_REMOVED") {
    lines.push(
      "- No candidate scored above the confidence threshold — the element was likely " +
        "removed or substantially redesigned. Confirm whether the test step is still valid.",
    );
  } else if (result.status === "AMBIGUOUS") {
    lines.push(
      "- Two or more candidates tied for the top score. Pick the intended one from the " +
        "table above and update the locator (preferably to a `getByRole`/`getByTestId`).",
    );
  } else {
    lines.push("- Inspect the candidates above and update the locator manually.");
  }
  lines.push(
    "- Prefer a semantic locator (`getByRole`, `getByTestId`) so the test survives the " +
      "next class/DOM refactor.",
  );
  lines.push("");
  lines.push("---");
  lines.push("_Filed by the `playwright-ui-locator` skill (no code was modified)._");
  return lines.join("\n") + "\n";
}

export async function buildGithubPlan(
  results: HealResult[],
  opts: GithubPlanOptions,
): Promise<GithubPlan> {
  const runId = opts.runId ?? compactTimestamp();
  const branchPrefix = opts.branchPrefix ?? "playwright-heal";
  const issueLabels = opts.issueLabels ?? ["playwright", "test-maintenance"];
  await mkdir(opts.outDir, { recursive: true });

  const healed = results.filter(
    (r): r is HealResult & { newLocator: string } =>
      r.status === "HEALED" && typeof r.newLocator === "string",
  );
  const needsIssue = results.filter((r) => r.status !== "HEALED");

  let pr: PrPlan | null = null;
  if (healed.length > 0) {
    const rewrites: PrRewrite[] = healed.map((r) => ({
      file: r.testFile,
      api: r.failing.api,
      old: r.failing.rawSelector,
      new: r.newLocator,
      confidence: r.confidence,
    }));
    const bodyFile = join(opts.outDir, "pr-body.md");
    await writeFile(bodyFile, renderPrBody(rewrites), "utf8");
    pr = {
      title: `Auto-heal ${rewrites.length} drifted Playwright locator${rewrites.length > 1 ? "s" : ""}`,
      bodyFile,
      branch: `${branchPrefix}/${runId}`,
      base: opts.base,
      rewrites,
    };
  }

  const issues: IssuePlan[] = [];
  for (let i = 0; i < needsIssue.length; i++) {
    const r = needsIssue[i];
    const bodyFile = join(opts.outDir, `issue-${i + 1}.md`);
    await writeFile(bodyFile, renderIssueBody(r), "utf8");
    issues.push({
      title: `Playwright locator drift in ${r.testFile}${r.failing.line ? `:${r.failing.line}` : ""} (${r.status})`,
      bodyFile,
      labels: issueLabels,
      status: r.status,
      testFile: r.testFile,
    });
  }

  const plan: GithubPlan = {
    pr,
    issues,
    repo: opts.repo,
    generatedAt: new Date().toISOString(),
  };

  await writeFile(join(opts.outDir, "plan.json"), JSON.stringify(plan, null, 2) + "\n", "utf8");
  return plan;
}
