"""Exit-code matrix — must mirror ../../../mjs/src/exit-codes.mjs byte-for-byte."""
from __future__ import annotations

EXIT_SUCCESS = 0
EXIT_GENERIC_FAILURE = 1
EXIT_MISUSE = 2
EXIT_PLAN_NOT_FOUND = 3
EXIT_PARSE_ERROR = 4
EXIT_CYCLE_DETECTED = 5
EXIT_BUDGET_EXCEEDED = 6
EXIT_HITL_PAUSE = 7
EXIT_GATE_FAILED = 8
EXIT_NOT_IMPLEMENTED = 100

EXIT_CODES: dict[str, int] = {
    "SUCCESS": EXIT_SUCCESS,
    "GENERIC_FAILURE": EXIT_GENERIC_FAILURE,
    "MISUSE": EXIT_MISUSE,
    "PLAN_NOT_FOUND": EXIT_PLAN_NOT_FOUND,
    "PARSE_ERROR": EXIT_PARSE_ERROR,
    "CYCLE_DETECTED": EXIT_CYCLE_DETECTED,
    "BUDGET_EXCEEDED": EXIT_BUDGET_EXCEEDED,
    "HITL_PAUSE": EXIT_HITL_PAUSE,
    "GATE_FAILED": EXIT_GATE_FAILED,
    "NOT_IMPLEMENTED": EXIT_NOT_IMPLEMENTED,
}
