export const EXIT_SUCCESS = 0;
export const EXIT_GENERIC_FAILURE = 1;
export const EXIT_MISUSE = 2;
export const EXIT_PLAN_NOT_FOUND = 3;
export const EXIT_PARSE_ERROR = 4;
export const EXIT_CYCLE_DETECTED = 5;
export const EXIT_BUDGET_EXCEEDED = 6;
export const EXIT_HITL_PAUSE = 7;
export const EXIT_GATE_FAILED = 8;
export const EXIT_NOT_IMPLEMENTED = 100;

export const EXIT_CODES = Object.freeze({
  SUCCESS: EXIT_SUCCESS,
  GENERIC_FAILURE: EXIT_GENERIC_FAILURE,
  MISUSE: EXIT_MISUSE,
  PLAN_NOT_FOUND: EXIT_PLAN_NOT_FOUND,
  PARSE_ERROR: EXIT_PARSE_ERROR,
  CYCLE_DETECTED: EXIT_CYCLE_DETECTED,
  BUDGET_EXCEEDED: EXIT_BUDGET_EXCEEDED,
  HITL_PAUSE: EXIT_HITL_PAUSE,
  GATE_FAILED: EXIT_GATE_FAILED,
  NOT_IMPLEMENTED: EXIT_NOT_IMPLEMENTED,
});
